### ISSUE TITLE
vsix install fails

### ISSUE THREAD

**Issue by julesx** [daishi4u/ForceCode#1]
![image](https://user-images.githubusercontent.com/3010047/41723162-5cb79a14-7538-11e8-9784-58df931888b1.png)

install log as follows: not sure why it doesn't detect my vs code...

21/06/2018 9:48:46 AM - Microsoft VSIX Installer
21/06/2018 9:48:46 AM - -------------------------------------------
21/06/2018 9:48:46 AM - vsixinstaller.exe version:
21/06/2018 9:48:46 AM - 15.7.105+ga2c5d563c6
21/06/2018 9:48:46 AM - -------------------------------------------
21/06/2018 9:48:46 AM - Command line parameters:
21/06/2018 9:48:46 AM - C:\program files (x86)\microsoft visual studio\installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\julesx\Downloads\forcecode-3.2.9.vsix
21/06/2018 9:48:46 AM - -------------------------------------------
21/06/2018 9:48:46 AM - Microsoft VSIX Installer
21/06/2018 9:48:46 AM - -------------------------------------------
21/06/2018 9:48:47 AM - Initializing Install...
21/06/2018 9:48:49 AM - Extension Details...
21/06/2018 9:48:49 AM - 	Identifier         : forcecode
21/06/2018 9:48:49 AM - 	Name               : ForceCode
21/06/2018 9:48:49 AM - 	Author             : BrettWagner
21/06/2018 9:48:49 AM - 	Version            : 3.2.9
21/06/2018 9:48:49 AM - 	Description        : Visual Studio Code extension for Salesforce (SFDC) development
21/06/2018 9:48:49 AM - 	Locale             : en-US
21/06/2018 9:48:49 AM - 	MoreInfoURL        : 
21/06/2018 9:48:49 AM - 	InstalledByMSI     : False
21/06/2018 9:48:49 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
21/06/2018 9:48:49 AM - 
21/06/2018 9:48:50 AM - 	SignatureState     : Unsigned
21/06/2018 9:48:52 AM - 	Supported Products : 
21/06/2018 9:48:52 AM - 		Microsoft.VisualStudio.Code
21/06/2018 9:48:52 AM - 			Version : 
21/06/2018 9:48:52 AM - 
21/06/2018 9:48:52 AM - 	References         : 
21/06/2018 9:48:52 AM - Signature Details...
21/06/2018 9:48:52 AM - 	Extension is not signed.
21/06/2018 9:48:52 AM - 
21/06/2018 9:48:52 AM - Searching for applicable products...
21/06/2018 9:48:52 AM - Found installed product - Global Location
21/06/2018 9:48:52 AM - Found installed product - Visual Studio Community 2017
21/06/2018 9:48:52 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

![image](https://user-images.githubusercontent.com/3010047/41723286-a8fd1372-7538-11e8-8722-388a0ab16226.png)

**Comment by julesx** [comment]
update: if i open the vsix from the extensions menu in vs code "install from vsix" it works
