### ISSUE TITLE
Exception when exiting "Retrieve Package/Metadata" menu

### ISSUE THREAD

**Issue by Bartheleway** [daishi4u/ForceCode#84]
Hi,

When selecting retrieve and then clicking somewhere else when ForceCode is prompting for the kind of retrieve we want to perform, we get an exception :

```
[error] Cannot read property 'message' of undefined: TypeError: Cannot read property 'message' of undefined
	at _1.switchUserViewService.checkLoginStatus.then.loggedIn (\.vscode\extensions\brettwagner.forcecode-3.8.4\out\src\services\commandView.js:73:59)
	at tryCatcher (\.vscode\extensions\brettwagner.forcecode-3.8.4\node_modules\bluebird\js\release\util.js:16:23)
	at Promise._settlePromiseFromHandler (\.vscode\extensions\brettwagner.forcecode-3.8.4\node_modules\bluebird\js\release\promise.js:510:31)
	at Promise._settlePromise (\.vscode\extensions\brettwagner.forcecode-3.8.4\node_modules\bluebird\js\release\promise.js:567:18)
	at Promise._settlePromise0 (\.vscode\extensions\brettwagner.forcecode-3.8.4\node_modules\bluebird\js\release\promise.js:612:10)
	at Promise._settlePromises (\.vscode\extensions\brettwagner.forcecode-3.8.4\node_modules\bluebird\js\release\promise.js:691:18)
	at Async._drainQueue (\.vscode\extensions\brettwagner.forcecode-3.8.4\node_modules\bluebird\js\release\async.js:138:16)
	at Async._drainQueues (\.vscode\extensions\brettwagner.forcecode-3.8.4\node_modules\bluebird\js\release\async.js:148:10)
	at Immediate.Async.drainQueues (\.vscode\extensions\brettwagner.forcecode-3.8.4\node_modules\bluebird\js\release\async.js:17:14)
	at runCallback (timers.js:789:20)
	at tryOnImmediate (timers.js:751:5)
	at processImmediate [as _immediateCallback] (timers.js:722:5)
```

Maybe obvious but I'm using :
- VS Code 1.27.1
- ForceCode 3.8.4

**Comment by daishi4u** [comment]
If it would be possible, could you try and retrieve all static resources only by doing it through the open function? Then let me know if you get this again. I believe your org may have a MIME type that isn't defined in my MIME dependency.

**Comment by daishi4u** [comment]
This is now fixed in v3.8.5

**Comment by Bartheleway** [comment]
Works well ! Thanks

**Comment by daishi4u** [comment]
You're welcome 😀
